from __future__ import annotations

from substrate._errors import ErrorCode

_STATUS_MAP: dict[str, int] = {
    ErrorCode.WORK_ITEM_NOT_FOUND: 404,
    ErrorCode.WORKFLOW_NOT_REGISTERED: 404,
    ErrorCode.CLAIM_NOT_FOUND: 404,
    ErrorCode.HOOK_NOT_FOUND: 404,
    ErrorCode.LINK_NOT_FOUND: 404,
    ErrorCode.LINK_TARGET_NOT_FOUND: 404,
    ErrorCode.ACTOR_ROLE_NOT_REGISTERED: 404,
    ErrorCode.RECURRENCE_RULE_NOT_FOUND: 404,
    ErrorCode.INVALID_TRANSITION: 400,
    ErrorCode.INVALID_FILTER: 400,
    ErrorCode.INVALID_ARGUMENT: 400,
    ErrorCode.INVALID_ACTOR_KIND: 400,
    ErrorCode.WORK_ITEM_TYPE_NOT_DECLARED: 400,
    ErrorCode.CUSTOM_FIELD_VIOLATION: 400,
    ErrorCode.TRANSITION_VIA_APPEND_BLOCKED: 400,
    ErrorCode.WORKFLOW_VALIDATION_FAILED: 400,
    ErrorCode.WORKFLOW_SEMANTIC_ERROR: 400,
    ErrorCode.LINK_TYPE_NOT_ALLOWED: 400,
    ErrorCode.LINK_CROSS_PROJECT: 400,
    ErrorCode.NOT_BEFORE_FUTURE: 400,
    ErrorCode.WORKFLOW_COMPOSE_ERROR: 400,
    ErrorCode.RECURRENCE_SCHEDULE_INVALID: 400,
    ErrorCode.RECURRENCE_TEMPLATE_INVALID: 400,
    ErrorCode.RECURRENCE_RULE_EXHAUSTED: 400,
    ErrorCode.LIBRARY_IS_SOLE_SIGNER: 400,
    ErrorCode.ROLE_NOT_PERMITTED: 403,
    ErrorCode.ACTOR_ROLE_NOT_AUTHORIZED: 403,
    ErrorCode.VALIDATOR_IO_UNSAFE: 403,
    ErrorCode.CLAIM_CONTESTED: 409,
    ErrorCode.CLAIM_LOST: 409,
    ErrorCode.CONCURRENT_MODIFICATION: 409,
    ErrorCode.WORKFLOW_VERSION_CONFLICT: 409,
    ErrorCode.IDEMPOTENCY_COLLISION_WITH_DIFFERENT_PAYLOAD: 409,
    ErrorCode.VALIDATOR_TIMEOUT: 504,
    ErrorCode.UNKNOWN_KEY_ID: 500,
    ErrorCode.REVOKED_KEY_ID: 500,
    ErrorCode.MIGRATION_REQUIRED: 500,
    ErrorCode.WORKFLOW_VERSION_INCOMPATIBLE: 500,
    ErrorCode.REPLAY_HALTED: 500,
    ErrorCode.DB_NOT_FOUND: 500,
    ErrorCode.VALIDATOR_FAILED: 500,
}


def error_to_status(code: ErrorCode) -> int:
    return _STATUS_MAP.get(code, 500)
