from enum import StrEnum


class ErrorCode(StrEnum):
    WORKFLOW_NOT_REGISTERED = "WORKFLOW_NOT_REGISTERED"
    WORK_ITEM_TYPE_NOT_DECLARED = "WORK_ITEM_TYPE_NOT_DECLARED"
    CUSTOM_FIELD_VIOLATION = "CUSTOM_FIELD_VIOLATION"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    ROLE_NOT_PERMITTED = "ROLE_NOT_PERMITTED"
    CLAIM_CONTESTED = "CLAIM_CONTESTED"
    CLAIM_LOST = "CLAIM_LOST"
    CLAIM_NOT_FOUND = "CLAIM_NOT_FOUND"
    NOT_BEFORE_FUTURE = "NOT_BEFORE_FUTURE"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    IDEMPOTENCY_COLLISION_WITH_DIFFERENT_PAYLOAD = "IDEMPOTENCY_COLLISION_WITH_DIFFERENT_PAYLOAD"
    UNKNOWN_KEY_ID = "UNKNOWN_KEY_ID"
    REVOKED_KEY_ID = "REVOKED_KEY_ID"
    WORKFLOW_VERSION_CONFLICT = "WORKFLOW_VERSION_CONFLICT"
    WORKFLOW_VALIDATION_FAILED = "WORKFLOW_VALIDATION_FAILED"
    WORKFLOW_SEMANTIC_ERROR = "WORKFLOW_SEMANTIC_ERROR"
    MIGRATION_REQUIRED = "MIGRATION_REQUIRED"
    WORKFLOW_VERSION_INCOMPATIBLE = "WORKFLOW_VERSION_INCOMPATIBLE"
    DB_NOT_FOUND = "DB_NOT_FOUND"
    LINK_TYPE_NOT_ALLOWED = "LINK_TYPE_NOT_ALLOWED"
    LINK_TARGET_NOT_FOUND = "LINK_TARGET_NOT_FOUND"
    LINK_CROSS_PROJECT = "LINK_CROSS_PROJECT"
    LINK_NOT_FOUND = "LINK_NOT_FOUND"
    WORK_ITEM_NOT_FOUND = "WORK_ITEM_NOT_FOUND"
    TRANSITION_VIA_APPEND_BLOCKED = "TRANSITION_VIA_APPEND_BLOCKED"
    REPLAY_HALTED = "REPLAY_HALTED"
    VALIDATOR_TIMEOUT = "VALIDATOR_TIMEOUT"
    VALIDATOR_FAILED = "VALIDATOR_FAILED"
    VALIDATOR_IO_UNSAFE = "VALIDATOR_IO_UNSAFE"
    HOOK_NOT_FOUND = "HOOK_NOT_FOUND"
    INVALID_FILTER = "INVALID_FILTER"
    INVALID_ACTOR_KIND = "INVALID_ACTOR_KIND"
    ACTOR_ROLE_NOT_AUTHORIZED = "ACTOR_ROLE_NOT_AUTHORIZED"
    ACTOR_ROLE_NOT_REGISTERED = "ACTOR_ROLE_NOT_REGISTERED"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"


class SubstrateError(Exception):
    def __init__(self, code: ErrorCode, message: str, detail: dict | None = None) -> None:
        self.code = code
        self.message = message
        self.detail = detail
        super().__init__(str(self))

    def __str__(self) -> str:
        return f"[{self.code}] {self.message}"
